language: java
sudo: required
services:
  - docker
script:
- mvn test -Dmaven.javadoc.skip=true -B
- cd redg-tests && mvn clean test -Dmaven.javadoc.skip=true -B
after_success:
- bash <(curl -s https://codecov.io/bash)