/*
 * This file was generated by RedG.
 * https://btc-ag.github.io/redg
 *       ____           ________
 *      / __ \___  ____/ / ____/
 *     / /_/ / _ \/ __  / / __
 *    / _, _/  __/ /_/ / /_/ /
 *   /_/ |_|\___/\__,_/\____/
 *
 * DO NOT EDIT MANUALLY!
 * Re-run the code generation to reflect database changes.
 */
package com.btc.redg.generated;

import java.util.ArrayList;
import java.util.List;

import com.btc.redg.runtime.*;
import com.btc.redg.models.*;

/**
 * <table summary="The table model attributes and their values">
 *     <tr>
 *         <td><strong>Attribute</strong></td>
 *         <td><strong>Value</strong></td>
 *     </tr>
 *     <tr>
 *         <td>Table name</td>
 *         <td>DEMO_COMPANY</td>
 *     </tr>
 *     <tr>
 *         <td>Full table name</td>
 *         <td>"RT-CG-MPFK".PUBLIC.DEMO_COMPANY</td>
 *     </tr>
 * </table>
 */
public class GDemoCompany implements RedGEntity {

    protected AbstractRedG redG;

    // do not manually make this public and instantiate it directly. Use the RedG Main class
    GDemoCompany(AbstractRedG redG) {
        this.redG = redG;
        try {
            this.countryCode = redG.getDefaultValueStrategy().getDefaultValue(getTableModel().getColumnBySQLName("COUNTRY_CODE"), java.lang.String.class);
            this.name = redG.getDefaultValueStrategy().getDefaultValue(getTableModel().getColumnBySQLName("NAME"), java.lang.String.class);

        } catch (Exception e) {
            throw new RuntimeException("Could not get default value", e);
        }
    }

    GDemoCompany(int meaningOfLife, AbstractRedG redG) {
        // First parameter exists simply because this constructor needs a different signature from the constructor above if the tables have no NOT NULL FK
        // Only for ExistingGDemoCompany , otherwise NOT NULL constraints cannot be checked and no default values are generated.
        this.redG = redG;
    }

    private java.lang.String countryCode;

    /**
     * <table summary="The column model attributes and their values">
     *     <tr>
     *         <td><strong>Attribute</strong></td>
     *         <td><strong>Value</strong></td>
     *     </tr>
     *     <tr>
     *         <td>Table name</td>
     *         <td>DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Full table name</td>
     *         <td>"RT-CG-MPFK".PUBLIC.DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Column name</td>
     *         <td>COUNTRY_CODE</td>
     *     </tr>
     *     <tr>
     *         <td>SQL type</td>
     *         <td>VARCHAR</td>
     *     </tr>
     *     <tr>
     *         <td>Not nullable?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Part of Primary key?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Unique?</td>
     *         <td>true</td>
     *     </tr>
     * </table>
     */
    public GDemoCompany countryCode(java.lang.String value) {
        if (value == null) {
            throw new IllegalArgumentException("Setting countryCode to null violates a NOT NULL constraint!");
        }
        this.countryCode = value;
        return this;
    }

    /**
     * <table summary="The column model attributes and their values">
     *     <tr>
     *         <td><strong>Attribute</strong></td>
     *         <td><strong>Value</strong></td>
     *     </tr>
     *     <tr>
     *         <td>Table name</td>
     *         <td>DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Full table name</td>
     *         <td>"RT-CG-MPFK".PUBLIC.DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Column name</td>
     *         <td>COUNTRY_CODE</td>
     *     </tr>
     *     <tr>
     *         <td>SQL type</td>
     *         <td>VARCHAR</td>
     *     </tr>
     *     <tr>
     *         <td>Not nullable?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Part of Primary key?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Unique?</td>
     *         <td>true</td>
     *     </tr>
     * </table>
     */
    public java.lang.String countryCode() {
        return this.countryCode;
    }

    private java.lang.String name;

    /**
     * <table summary="The column model attributes and their values">
     *     <tr>
     *         <td><strong>Attribute</strong></td>
     *         <td><strong>Value</strong></td>
     *     </tr>
     *     <tr>
     *         <td>Table name</td>
     *         <td>DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Full table name</td>
     *         <td>"RT-CG-MPFK".PUBLIC.DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Column name</td>
     *         <td>NAME</td>
     *     </tr>
     *     <tr>
     *         <td>SQL type</td>
     *         <td>VARCHAR</td>
     *     </tr>
     *     <tr>
     *         <td>Not nullable?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Part of Primary key?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Unique?</td>
     *         <td>true</td>
     *     </tr>
     * </table>
     */
    public GDemoCompany name(java.lang.String value) {
        if (value == null) {
            throw new IllegalArgumentException("Setting name to null violates a NOT NULL constraint!");
        }
        this.name = value;
        return this;
    }

    /**
     * <table summary="The column model attributes and their values">
     *     <tr>
     *         <td><strong>Attribute</strong></td>
     *         <td><strong>Value</strong></td>
     *     </tr>
     *     <tr>
     *         <td>Table name</td>
     *         <td>DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Full table name</td>
     *         <td>"RT-CG-MPFK".PUBLIC.DEMO_COMPANY</td>
     *     </tr>
     *     <tr>
     *         <td>Column name</td>
     *         <td>NAME</td>
     *     </tr>
     *     <tr>
     *         <td>SQL type</td>
     *         <td>VARCHAR</td>
     *     </tr>
     *     <tr>
     *         <td>Not nullable?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Part of Primary key?</td>
     *         <td>true</td>
     *     </tr>
     *     <tr>
     *         <td>Unique?</td>
     *         <td>true</td>
     *     </tr>
     * </table>
     */
    public java.lang.String name() {
        return this.name;
    }


    public List<RedGEntity> getDependencies() {
        List<RedGEntity> dependencies = new ArrayList<>();
        return dependencies;
    }

    public List<GDemoUser> demoUsersForCompany() {
        return this.redG.findEntities(GDemoUser.class, gEntity -> ((GDemoUser) gEntity).company() == this);
    }

    public GDemoCompany addDemoUsersForCompany(GDemoUser... objects) {
        for (GDemoUser obj : objects) {
            obj.company(this);
        }
        return this;
    }


    public String getSQLString() {
        return String.format("INSERT INTO DEMO_COMPANY (" +
                        "" +
                        "" +
                        "COUNTRY_CODE, NAME" +
                        ") VALUES (" +
                        "" +
                        "" +
                        "%s, %s)",
                this.redG.getSqlValuesFormatter().formatValue(this.countryCode(),
                        "VARCHAR", "\"RT-CG-MPFK\".PUBLIC.DEMO_COMPANY",
                        "DEMO_COMPANY", "COUNTRY_CODE"),
                this.redG.getSqlValuesFormatter().formatValue(this.name(),
                        "VARCHAR", "\"RT-CG-MPFK\".PUBLIC.DEMO_COMPANY",
                        "DEMO_COMPANY", "NAME")
        );
    }

    public String getPreparedStatementString() {
        return "INSERT INTO DEMO_COMPANY (" +
                "" +
                "" +
                "COUNTRY_CODE, NAME" +
                ") VALUES (" +
                "" +
                "" +
                "?, ?)";
    }

    public Object[] getPreparedStatementValues() {
        return new Object[]{
                this.countryCode(),
                this.name()
        };
    }

    public AttributeMetaInfo[] getPreparedStatementValuesMetaInfos() {
        return new AttributeMetaInfo[]{
                new AttributeMetaInfo("COUNTRY_CODE", "DEMO_COMPANY", "DEMO_COMPANY", "VARCHAR", 12, java.lang.String.class, true),
                new AttributeMetaInfo("NAME", "DEMO_COMPANY", "DEMO_COMPANY", "VARCHAR", 12, java.lang.String.class, true)
        };
    }

    private static String serializedTableModel = "rO0ABXNyAB5jb20uYnRjLnJlZGcubW9kZWxzLlRhYmxlTW9kZWx0b/Ys7hpPuAIACloAGGhhc0NvbHVtbnNBbmRGb3JlaWduS2V5c0wACWNsYXNzTmFtZXQAEkxqYXZhL2xhbmcvU3RyaW5nO0wAB2NvbHVtbnN0ABBMamF2YS91dGlsL0xpc3Q7TAALZm9yZWlnbktleXNxAH4AAkwAE2luY29taW5nRm9yZWlnbktleXNxAH4AAkwAF2pvaW5UYWJsZVNpbXBsaWZpZXJEYXRhdAAPTGphdmEvdXRpbC9NYXA7TAAEbmFtZXEAfgABTAALcGFja2FnZU5hbWVxAH4AAUwAC3NxbEZ1bGxOYW1lcQB+AAFMAAdzcWxOYW1lcQB+AAF4cAB0AAxHRGVtb0NvbXBhbnlzcgATamF2YS51dGlsLkFycmF5TGlzdHiB0h2Zx2GdAwABSQAEc2l6ZXhwAAAAAncEAAAAAnNyAB9jb20uYnRjLnJlZGcubW9kZWxzLkNvbHVtbk1vZGVsZ6XLR7cE1PwCAA1aABFleHBsaWNpdEF0dHJpYnV0ZVoAB25vdE51bGxaABBwYXJ0T2ZGb3JlaWduS2V5WgAQcGFydE9mUHJpbWFyeUtleUkACnNxbFR5cGVJbnRaAAZ1bmlxdWVMABJjb252ZW5pZW5jZVNldHRlcnNxAH4AAkwAD2RiRnVsbFRhYmxlTmFtZXEAfgABTAAGZGJOYW1lcQB+AAFMAAtkYlRhYmxlTmFtZXEAfgABTAAMamF2YVR5cGVOYW1lcQB+AAFMAARuYW1lcQB+AAFMAAdzcWxUeXBlcQB+AAF4cAABAAEAAAAMAXNyAB9qYXZhLnV0aWwuQ29sbGVjdGlvbnMkRW1wdHlMaXN0ergXtDynnt4CAAB4cHQAICJSVC1DRy1NUEZLIi5QVUJMSUMuREVNT19DT01QQU5ZdAAMQ09VTlRSWV9DT0RFdAAMREVNT19DT01QQU5ZdAAQamF2YS5sYW5nLlN0cmluZ3QAC2NvdW50cnlDb2RldAAHVkFSQ0hBUnNxAH4ACAABAAEAAAAMAXEAfgALdAAgIlJULUNHLU1QRksiLlBVQkxJQy5ERU1PX0NPTVBBTll0AAROQU1FcQB+AA5xAH4AD3QABG5hbWVxAH4AEXhzcQB+AAYAAAAAdwQAAAAAeHNxAH4ABgAAAAF3BAAAAAFzcgArY29tLmJ0Yy5yZWRnLm1vZGVscy5JbmNvbWluZ0ZvcmVpZ25LZXlNb2RlbIOEJFLnwObUAgAFWgAHbm90TnVsbEwADWF0dHJpYnV0ZU5hbWVxAH4AAUwAGHJlZmVyZW5jaW5nQXR0cmlidXRlTmFtZXEAfgABTAAVcmVmZXJlbmNpbmdFbnRpdHlOYW1lcQB+AAFMABdyZWZlcmVuY2luZ0phdmFUeXBlTmFtZXEAfgABeHAAdAATZGVtb1VzZXJzRm9yQ29tcGFueXQAB2NvbXBhbnl0AAhEZW1vVXNlcnQACUdEZW1vVXNlcnhzcgARamF2YS51dGlsLkhhc2hNYXAFB9rBwxZg0QMAAkYACmxvYWRGYWN0b3JJAAl0aHJlc2hvbGR4cD9AAAAAAAAAdwgAAAAQAAAAAHh0AAtEZW1vQ29tcGFueXQAFmNvbS5idGMucmVkZy5nZW5lcmF0ZWR0ACAiUlQtQ0ctTVBGSyIuUFVCTElDLkRFTU9fQ09NUEFOWXEAfgAO";
    private static TableModel tableModel;

    public static String getSerializedTableModel() {
        return serializedTableModel;
    }

    public static TableModel getTableModel() {
        if (tableModel == null) {
            byte[] data = java.util.Base64.getDecoder().decode(serializedTableModel);
            try {
                java.io.ObjectInputStream ois = new java.io.ObjectInputStream(new java.io.ByteArrayInputStream(data));
                tableModel = (TableModel) ois.readObject();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        return tableModel;
    }
}