/*
 * This file was generated by RedG.
 * https://btc-redg.github.com/
 *       ____           ________
 *      / __ \___  ____/ / ____/
 *     / /_/ / _ \/ __  / / __
 *    / _, _/  __/ /_/ / /_/ /
 *   /_/ |_|\___/\__,_/\____/
 *
 * DO NOT EDIT MANUALLY!
 * Re-run the code generation to reflect database changes.
 */
package com.btc.redg.generated;

import com.btc.redg.runtime.*;

/**
 * {@inheritDoc}
 */
public class ExistingGDemoCompany extends GDemoCompany {

    ExistingGDemoCompany(AbstractRedG redG, java.lang.String countryCode, java.lang.String name) {
        super(42, redG);
        super.countryCode(countryCode);
        super.name(name);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GDemoCompany countryCode(java.lang.String value) {
        throw new UnsupportedOperationException("Cannot change values of entities declared as existing.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String countryCode() {
        return super.countryCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GDemoCompany name(java.lang.String value) {
        throw new UnsupportedOperationException("Cannot change values of entities declared as existing.");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public java.lang.String name() {
        return super.name();
    }



    @Override
    public String getSQLString() {
        return String.format("SELECT COUNT(*) FROM DEMO_COMPANY WHERE " +
                        "COUNTRY_CODE = %s AND NAME = %s",
                this.redG.getSqlValuesFormatter().formatValue(super.countryCode(),
                        "VARCHAR", "\"RT-CG-MPFK\".PUBLIC.DEMO_COMPANY",
                        "DEMO_COMPANY", "COUNTRY_CODE"),
                this.redG.getSqlValuesFormatter().formatValue(super.name(),
                        "VARCHAR", "\"RT-CG-MPFK\".PUBLIC.DEMO_COMPANY",
                        "DEMO_COMPANY", "NAME")
        );
    }

    @Override
    public String getPreparedStatementString() {
        return "SELECT COUNT(*) FROM DEMO_COMPANY WHERE " +
                "COUNTRY_CODE = ? AND " +
                "NAME = ?";
    }

    @Override
    public Object[] getPreparedStatementValues() {
        return new Object[] {
                super.countryCode(),
                super.name()
        };
    }

    @Override
    public AttributeMetaInfo[] getPreparedStatementValuesMetaInfos() {
        return new AttributeMetaInfo[] {
                new AttributeMetaInfo("COUNTRY_CODE", "DEMO_COMPANY", "\"RT-CG-MPFK\".PUBLIC.DEMO_COMPANY", "VARCHAR", 12, java.lang.String.class, true),
                new AttributeMetaInfo("NAME", "DEMO_COMPANY", "\"RT-CG-MPFK\".PUBLIC.DEMO_COMPANY", "VARCHAR", 12, java.lang.String.class, true)
        };
    }
}