-- Test

CREATE TABLE DEMO_COMPANY (
  ID   NUMBER(19)        NOT NULL,
  NAME VARCHAR2(30 CHAR) NOT NULL,

  CONSTRAINT pk_DEMO_COMPANY PRIMARY KEY (ID)
);

CREATE TABLE DEMO_USER (
  DTYPE      VARCHAR2(32 CHAR) NOT NULL,
  ID         NUMBER(19)        NOT NULL,
  USERNAME   VARCHAR2(30 CHAR) NOT NULL,
  FIRST_NAME VARCHAR2(50 CHAR),
  LAST_NAME  VARCHAR2(50 CHAR),
  WORKS_AT   NUMBER(19)        NOT NULL,
  DAY        timestamp,

  CONSTRAINT pk_DEMO_USER PRIMARY KEY (ID),
  CONSTRAINT fk_DEMO_USER_COMPANY FOREIGN KEY (WORKS_AT) REFERENCES DEMO_COMPANY(ID)
);

