
CREATE TABLE DEMO_COMPANY (
  ID   NUMBER(19)        NOT NULL,
  NAME VARCHAR2(30 CHAR) NOT NULL,

  CONSTRAINT pk_DEMO_COMPANY PRIMARY KEY (ID)
);

CREATE TABLE DEMO_USER (
  ID         NUMBER(19)        NOT NULL,
  USERNAME   VARCHAR2(30 CHAR) NOT NULL,
  FIRST_NAME VARCHAR2(50 CHAR),
  LAST_NAME  VARCHAR2(50 CHAR),

  CONSTRAINT pk_DEMO_USER PRIMARY KEY (ID),
);

CREATE TABLE USER_WORKS_AT_COMPANIES (
  ID NUMBER(19) NOT NULL ,
  USER_ID NUMBER(19) NOT NULL ,
  COMPANY_ID NUMBER(19) NOT NULL ,

  CONSTRAINT pk_U_W_A_C PRIMARY KEY (ID),
  CONSTRAINT FK_WORKS_AT_COMPANY FOREIGN KEY (COMPANY_ID) REFERENCES DEMO_COMPANY(ID),
  CONSTRAINT FK_USER_WORKS FOREIGN KEY (USER_ID) REFERENCES DEMO_USER(ID)
);

create or replace view X as (select USERNAME from DEMO_USER);