
CREATE TABLE DATES_TABLE (
  A_DATE date,
  A_TIME time,
  A_TIMESTAMP timestamp NOT NULL,
  A_TIMESTAMP_WTZ TIMESTAMP WITH TIME ZONE,

  B_DATE date,
  B_TIME time,
  B_TIMESTAMP timestamp NOT NULL,
  B_TIMESTAMP_WTZ TIMESTAMP WITH TIME ZONE
);
