-- Test

CREATE TABLE DEMO_COMPANY (
  COUNTRY_CODE VARCHAR2(2 CHAR)  NOT NULL,
  NAME         VARCHAR2(30 CHAR) NOT NULL,

  CONSTRAINT pk_DEMO_COMPANY PRIMARY KEY (COUNTRY_CODE, NAME)
);

CREATE TABLE DEMO_BANK_ACCOUNT (
  BIC  VARCHAR2(11 CHAR) NOT NULL,
  IBAN VARCHAR2(22 CHAR) NOT NULL,

  CONSTRAINT pk_DEMO_BANK_ACCOUNT PRIMARY KEY (BIC, IBAN)
);

CREATE TABLE DEMO_USER (
  ID            NUMBER(19)        NOT NULL,
  USERNAME      VARCHAR2(30 CHAR) NOT NULL,
  FIRST_NAME    VARCHAR2(50 CHAR),
  LAST_NAME     VARCHAR2(50 CHAR),
  WORKS_AT_CC   VARCHAR2(2 CHAR)  NOT NULL,
  WORKS_AT_NAME VARCHAR2(30 CHAR) NOT NULL,
  ACC_BIC  VARCHAR2(11 CHAR) NOT NULL,
  ACC_IBAN VARCHAR2(22 CHAR) NOT NULL,

  CONSTRAINT pk_DEMO_USER PRIMARY KEY (ID),
  CONSTRAINT fk_DEMO_USER_COMPANY FOREIGN KEY (WORKS_AT_CC, WORKS_AT_NAME) REFERENCES DEMO_COMPANY (COUNTRY_CODE, NAME),
  CONSTRAINT fk_DEMO_USER_BANK_ACC FOREIGN KEY (ACC_BIC, ACC_IBAN) REFERENCES DEMO_BANK_ACCOUNT(BIC, IBAN)
);

